postgres:
  image: "testcontainers/postgres:latest"
  port: 5432

mongo:
  image: "testcontainers/mongo:latest"
  port: 27017

rabbitmq:
  image: "testcontainers/rabbitmq:latest"
  port: 5672

zookeeper:
  replicas: 1
  image: confluentinc/cp-zookeeper:6.1.0
  ports:
    client: 2181

kafka:
  replicas: 1
  image: confluentinc/cp-kafka:6.1.0
  ports:
    internal: 9092
  zookeeperConnect: "zookeeper:2181"
  offsetReplicationFactor: 1

